apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: us.gcr.io/ticekting-dev-395414/auth
      #    - image: chariss/ticketing-auth
      context: auth
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
  #  local:
  #    push: false
  googleCloudBuild:
    projectId: ticekting-dev-395414
manifests:
  rawYaml:
    - ./infra/k8s/*