apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: chariss/auth
      context: auth
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: chariss/tickets
      context: tickets
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: chariss/orders
      context: orders
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: chariss/client
      context: client
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: chariss/expiration
      context: expiration
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s-local/*
