apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: chariss/ticketing-auth
      context: auth
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: us.gcr.io/ticekting-dev-395414/client
      context: client
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*